version: "3"

services:
  # Redis service
  redis:
    container_name: redis_container
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - redis_network
    restart: unless-stopped

  # Postgres service
  postgres:
    container_name: postgres_container
    image: postgres
    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  # pgAdmin service
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
